name: Upload Go test results

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go get .
    - name: Test with Go
      run: go test -json > TestResults-${{ matrix.go-version }}.json
    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
